name: pathfinder_flutter
description: Pathfinder Flutter client
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <4.0.0"
    flutter: ">=3.7.0"

dependencies:
    flutter:
        sdk: flutter
    serverpod_flutter: ^1.1.1
    pathfinder_client:
        path: ../pathfinder_client
    cupertino_icons: ^1.0.5
    google_fonts: ^4.0.4
    feather_icons: ^1.2.0
    flutter_map: ^4.0.0
    geocoding: ^2.1.1
    geolocator: ^10.1.0
    http: ^0.13.6
    latlong2: ^0.8.2
    hive: ^2.2.3
    hive_flutter: ^1.1.0

dev_dependencies:
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    change_app_package_name: ^1.1.0
    hive_generator: ^2.0.1
    build_runner: ^2.4.6

flutter:
    uses-material-design: true
